export const voiceOptions = [
  { value: "en-US-Ana", label: "English (United States) - Ana" },
  { value: "en-US-AndrewMultilingual", label: "English (United States) - AndrewMultilingual" },
  { value: "en-US-Andrew", label: "English (United States) - Andrew" },
  { value: "en-US-Aria", label: "English (United States) - Aria" },
  { value: "en-US-AvaMultilingual", label: "English (United States) - AvaMultilingual" },
  { value: "en-US-Ava", label: "English (United States) - Ava" },
  { value: "en-US-BrianMultilingual", label: "English (United States) - BrianMultilingual" },
  { value: "en-US-Brian", label: "English (United States) - Brian" },
  { value: "en-US-Christopher", label: "English (United States) - Christopher" },
  { value: "en-US-EmmaMultilingual", label: "English (United States) - EmmaMultilingual" },
  { value: "en-US-Emma", label: "English (United States) - Emma" },
  { value: "en-US-Eric", label: "English (United States) - Eric" },
  { value: "en-US-Guy", label: "English (United States) - Guy" },
  { value: "en-US-Jenny", label: "English (United States) - Jenny" },
  { value: "en-US-Michelle", label: "English (United States) - Michelle" },
  { value: "en-US-Roger", label: "English (United States) - Roger" },
  { value: "en-US-Steffan", label: "English (United States) - Steffan" },
  { value: "af-ZA-Adri", label: "Afrikaans (South Africa) - Adri" },
  { value: "af-ZA-Willem", label: "Afrikaans (South Africa) - Willem" },
  { value: "am-ET-Ameha", label: "Amharic (Ethiopia) - Ameha" },
  { value: "am-ET-Mekdes", label: "Amharic (Ethiopia) - Mekdes" },
  { value: "ar-AE-Fatima", label: "Arabic (United Arab Emirates) - Fatima" },
  { value: "ar-AE-Hamdan", label: "Arabic (United Arab Emirates) - Hamdan" },
  { value: "ar-BH-Ali", label: "Arabic (Bahrain) - Ali" },
  { value: "ar-BH-Laila", label: "Arabic (Bahrain) - Laila" },
  { value: "ar-DZ-Amina", label: "Arabic (Algeria) - Amina" },
  { value: "ar-DZ-Ismael", label: "Arabic (Algeria) - Ismael" },
  { value: "ar-EG-Salma", label: "Arabic (Egypt) - Salma" },
  { value: "ar-EG-Shakir", label: "Arabic (Egypt) - Shakir" },
  { value: "ar-IQ-Bassel", label: "Arabic (Iraq) - Bassel" },
  { value: "ar-IQ-Rana", label: "Arabic (Iraq) - Rana" },
  { value: "ar-JO-Sana", label: "Arabic (Jordan) - Sana" },
  { value: "ar-JO-Taim", label: "Arabic (Jordan) - Taim" },
  { value: "ar-KW-Fahed", label: "Arabic (Kuwait) - Fahed" },
  { value: "ar-KW-Noura", label: "Arabic (Kuwait) - Noura" },
  { value: "ar-LB-Layla", label: "Arabic (Lebanon) - Layla" },
  { value: "ar-LB-Rami", label: "Arabic (Lebanon) - Rami" },
  { value: "ar-LY-Iman", label: "Arabic (Libya) - Iman" },
  { value: "ar-LY-Omar", label: "Arabic (Libya) - Omar" },
  { value: "ar-MA-Jamal", label: "Arabic (Morocco) - Jamal" },
  { value: "ar-MA-Mouna", label: "Arabic (Morocco) - Mouna" },
  { value: "ar-OM-Abdullah", label: "Arabic (Oman) - Abdullah" },
  { value: "ar-OM-Aysha", label: "Arabic (Oman) - Aysha" },
  { value: "ar-QA-Amal", label: "Arabic (Qatar) - Amal" },
  { value: "ar-QA-Moaz", label: "Arabic (Qatar) - Moaz" },
  { value: "ar-SA-Hamed", label: "Arabic (Saudi Arabia) - Hamed" },
  { value: "ar-SA-Zariyah", label: "Arabic (Saudi Arabia) - Zariyah" },
  { value: "ar-SY-Amany", label: "Arabic (Syria) - Amany" },
  { value: "ar-SY-Laith", label: "Arabic (Syria) - Laith" },
  { value: "ar-TN-Hedi", label: "Arabic (Tunisia) - Hedi" },
  { value: "ar-TN-Reem", label: "Arabic (Tunisia) - Reem" },
  { value: "ar-YE-Maryam", label: "Arabic (Yemen) - Maryam" },
  { value: "ar-YE-Saleh", label: "Arabic (Yemen) - Saleh" },
  { value: "az-AZ-Babek", label: "Azerbaijani (Azerbaijan) - Babek" },
  { value: "az-AZ-Banu", label: "Azerbaijani (Azerbaijan) - Banu" },
  { value: "bg-BG-Borislav", label: "Bulgarian (Bulgaria) - Borislav" },
  { value: "bg-BG-Kalina", label: "Bulgarian (Bulgaria) - Kalina" },
  { value: "bn-BD-Nabanita", label: "Bangla (Bangladesh) - Nabanita" },
  { value: "bn-BD-Pradeep", label: "Bangla (Bangladesh) - Pradeep" },
  { value: "bn-IN-Bashkar", label: "Bangla (India) - Bashkar" },
  { value: "bn-IN-Tanishaa", label: "Bangla (India) - Tanishaa" },
  { value: "bs-BA-Goran", label: "Bosnian (Bosnia and Herzegovina) - Goran" },
  { value: "bs-BA-Vesna", label: "Bosnian (Bosnia and Herzegovina) - Vesna" },
  { value: "ca-ES-Enric", label: "Catalan (Spain) - Enric" },
  { value: "ca-ES-Joana", label: "Catalan (Spain) - Joana" },
  { value: "cs-CZ-Antonin", label: "Czech (Czech Republic) - Antonin" },
  { value: "cs-CZ-Vlasta", label: "Czech (Czech Republic) - Vlasta" },
  { value: "cy-GB-Aled", label: "Welsh (United Kingdom) - Aled" },
  { value: "cy-GB-Nia", label: "Welsh (United Kingdom) - Nia" },
  { value: "da-DK-Christel", label: "Danish (Denmark) - Christel" },
  { value: "da-DK-Jeppe", label: "Danish (Denmark) - Jeppe" },
  { value: "de-AT-Ingrid", label: "German (Austria) - Ingrid" },
  { value: "de-AT-Jonas", label: "German (Austria) - Jonas" },
  { value: "de-CH-Jan", label: "German (Switzerland) - Jan" },
  { value: "de-CH-Leni", label: "German (Switzerland) - Leni" },
  { value: "de-DE-Amala", label: "German (Germany) - Amala" },
  { value: "de-DE-Conrad", label: "German (Germany) - Conrad" },
  { value: "de-DE-FlorianMultilingual", label: "German (Germany) - FlorianMultilingual" },
  { value: "de-DE-Katja", label: "German (Germany) - Katja" },
  { value: "de-DE-Killian", label: "German (Germany) - Killian" },
  { value: "de-DE-SeraphinaMultilingual", label: "German (Germany) - SeraphinaMultilingual" },
  { value: "el-GR-Athina", label: "Greek (Greece) - Athina" },
  { value: "el-GR-Nestoras", label: "Greek (Greece) - Nestoras" },
  { value: "en-AU-Natasha", label: "English (Australia) - Natasha" },
  { value: "en-AU-William", label: "English (Australia) - William" },
  { value: "en-CA-Clara", label: "English (Canada) - Clara" },
  { value: "en-CA-Liam", label: "English (Canada) - Liam" },
  { value: "en-GB-Libby", label: "English (United Kingdom) - Libby" },
  { value: "en-GB-Maisie", label: "English (United Kingdom) - Maisie" },
  { value: "en-GB-Ryan", label: "English (United Kingdom) - Ryan" },
  { value: "en-GB-Sonia", label: "English (United Kingdom) - Sonia" },
  { value: "en-GB-Thomas", label: "English (United Kingdom) - Thomas" },
  { value: "en-HK-Sam", label: "English (Hong Kong) - Sam" },
  { value: "en-HK-Yan", label: "English (Hong Kong) - Yan" },
  { value: "en-IE-Connor", label: "English (Ireland) - Connor" },
  { value: "en-IE-Emily", label: "English (Ireland) - Emily" },
  { value: "en-IN-NeerjaExpressive", label: "English (India) - NeerjaExpressive" },
  { value: "en-IN-Neerja", label: "English (India) - Neerja" },
  { value: "en-IN-Prabhat", label: "English (India) - Prabhat" },
  { value: "en-KE-Asilia", label: "English (Kenya) - Asilia" },
  { value: "en-KE-Chilemba", label: "English (Kenya) - Chilemba" },
  { value: "en-NG-Abeo", label: "English (Nigeria) - Abeo" },
  { value: "en-NG-Ezinne", label: "English (Nigeria) - Ezinne" },
  { value: "en-NZ-Mitchell", label: "English (New Zealand) - Mitchell" },
  { value: "en-NZ-Molly", label: "English (New Zealand) - Molly" },
  { value: "en-PH-James", label: "English (Philippines) - James" },
  { value: "en-PH-Rosa", label: "English (Philippines) - Rosa" },
  { value: "en-SG-Luna", label: "English (Singapore) - Luna" },
  { value: "en-SG-Wayne", label: "English (Singapore) - Wayne" },
  { value: "en-TZ-Elimu", label: "English (Tanzania) - Elimu" },
  { value: "en-TZ-Imani", label: "English (Tanzania) - Imani" },
  { value: "en-ZA-Leah", label: "English (South Africa) - Leah" },
  { value: "en-ZA-Luke", label: "English (South Africa) - Luke" },
  { value: "es-AR-Elena", label: "Spanish (Argentina) - Elena" },
  { value: "es-AR-Tomas", label: "Spanish (Argentina) - Tomas" },
  { value: "es-BO-Marcelo", label: "Spanish (Bolivia) - Marcelo" },
  { value: "es-BO-Sofia", label: "Spanish (Bolivia) - Sofia" },
  { value: "es-CL-Catalina", label: "Spanish (Chile) - Catalina" },
  { value: "es-CL-Lorenzo", label: "Spanish (Chile) - Lorenzo" },
  { value: "es-CO-Gonzalo", label: "Spanish (Colombia) - Gonzalo" },
  { value: "es-CO-Salome", label: "Spanish (Colombia) - Salome" },
  { value: "es-CR-Juan", label: "Spanish (Costa Rica) - Juan" },
  { value: "es-CR-Maria", label: "Spanish (Costa Rica) - Maria" },
  { value: "es-CU-Belkys", label: "Spanish (Cuba) - Belkys" },
  { value: "es-CU-Manuel", label: "Spanish (Cuba) - Manuel" },
  { value: "es-DO-Emilio", label: "Spanish (Dominican Republic) - Emilio" },
  { value: "es-DO-Ramona", label: "Spanish (Dominican Republic) - Ramona" },
  { value: "es-EC-Andrea", label: "Spanish (Ecuador) - Andrea" },
  { value: "es-EC-Luis", label: "Spanish (Ecuador) - Luis" },
  { value: "es-ES-Alvaro", label: "Spanish (Spain) - Alvaro" },
  { value: "es-ES-Elvira", label: "Spanish (Spain) - Elvira" },
  { value: "es-ES-Ximena", label: "Spanish (Spain) - Ximena" },
  { value: "es-GQ-Javier", label: "Spanish (Equatorial Guinea) - Javier" },
  { value: "es-GQ-Teresa", label: "Spanish (Equatorial Guinea) - Teresa" },
  { value: "es-GT-Andres", label: "Spanish (Guatemala) - Andres" },
  { value: "es-GT-Marta", label: "Spanish (Guatemala) - Marta" },
  { value: "es-HN-Carlos", label: "Spanish (Honduras) - Carlos" },
  { value: "es-HN-Karla", label: "Spanish (Honduras) - Karla" },
  { value: "es-MX-Dalia", label: "Spanish (Mexico) - Dalia" },
  { value: "es-MX-Jorge", label: "Spanish (Mexico) - Jorge" },
  { value: "es-NI-Federico", label: "Spanish (Nicaragua) - Federico" },
  { value: "es-NI-Yolanda", label: "Spanish (Nicaragua) - Yolanda" },
  { value: "es-PA-Margarita", label: "Spanish (Panama) - Margarita" },
  { value: "es-PA-Roberto", label: "Spanish (Panama) - Roberto" },
  { value: "es-PE-Alex", label: "Spanish (Peru) - Alex" },
  { value: "es-PE-Camila", label: "Spanish (Peru) - Camila" },
  { value: "es-PR-Karina", label: "Spanish (Puerto Rico) - Karina" },
  { value: "es-PR-Victor", label: "Spanish (Puerto Rico) - Victor" },
  { value: "es-PY-Mario", label: "Spanish (Paraguay) - Mario" },
  { value: "es-PY-Tania", label: "Spanish (Paraguay) - Tania" },
  { value: "es-SV-Lorena", label: "Spanish (El Salvador) - Lorena" },
  { value: "es-SV-Rodrigo", label: "Spanish (El Salvador) - Rodrigo" },
  { value: "es-US-Alonso", label: "Spanish (United States) - Alonso" },
  { value: "es-US-Paloma", label: "Spanish (United States) - Paloma" },
  { value: "es-UY-Mateo", label: "Spanish (Uruguay) - Mateo" },
  { value: "es-UY-Valentina", label: "Spanish (Uruguay) - Valentina" },
  { value: "es-VE-Paola", label: "Spanish (Venezuela) - Paola" },
  { value: "es-VE-Sebastian", label: "Spanish (Venezuela) - Sebastian" },
  { value: "et-EE-Anu", label: "Estonian (Estonia) - Anu" },
  { value: "et-EE-Kert", label: "Estonian (Estonia) - Kert" },
  { value: "fa-IR-Dilara", label: "Persian (Iran) - Dilara" },
  { value: "fa-IR-Farid", label: "Persian (Iran) - Farid" },
  { value: "fi-FI-Harri", label: "Finnish (Finland) - Harri" },
  { value: "fi-FI-Noora", label: "Finnish (Finland) - Noora" },
  { value: "fil-PH-Angelo", label: "Filipino (Philippines) - Angelo" },
  { value: "fil-PH-Blessica", label: "Filipino (Philippines) - Blessica" },
  { value: "fr-BE-Charline", label: "French (Belgium) - Charline" },
  { value: "fr-BE-Gerard", label: "French (Belgium) - Gerard" },
  { value: "fr-CA-Antoine", label: "French (Canada) - Antoine" },
  { value: "fr-CA-Jean", label: "French (Canada) - Jean" },
  { value: "fr-CA-Sylvie", label: "French (Canada) - Sylvie" },
  { value: "fr-CA-Thierry", label: "French (Canada) - Thierry" },
  { value: "fr-CH-Ariane", label: "French (Switzerland) - Ariane" },
  { value: "fr-CH-Fabrice", label: "French (Switzerland) - Fabrice" },
  { value: "fr-FR-Denise", label: "French (France) - Denise" },
  { value: "fr-FR-Eloise", label: "French (France) - Eloise" },
  { value: "fr-FR-Henri", label: "French (France) - Henri" },
  { value: "fr-FR-RemyMultilingual", label: "French (France) - RemyMultilingual" },
  { value: "fr-FR-VivienneMultilingual", label: "French (France) - VivienneMultilingual" },
  { value: "ga-IE-Colm", label: "Irish (Ireland) - Colm" },
  { value: "ga-IE-Orla", label: "Irish (Ireland) - Orla" },
  { value: "gl-ES-Roi", label: "Galician (Spain) - Roi" },
  { value: "gl-ES-Sabela", label: "Galician (Spain) - Sabela" },
  { value: "gu-IN-Dhwani", label: "Gujarati (India) - Dhwani" },
  { value: "gu-IN-Niranjan", label: "Gujarati (India) - Niranjan" },
  { value: "he-IL-Avri", label: "Hebrew (Israel) - Avri" },
  { value: "he-IL-Hila", label: "Hebrew (Israel) - Hila" },
  { value: "hi-IN-Madhur", label: "Hindi (India) - Madhur" },
  { value: "hi-IN-Swara", label: "Hindi (India) - Swara" },
  { value: "hr-HR-Gabrijela", label: "Croatian (Croatia) - Gabrijela" },
  { value: "hr-HR-Srecko", label: "Croatian (Croatia) - Srecko" },
  { value: "hu-HU-Noemi", label: "Hungarian (Hungary) - Noemi" },
  { value: "hu-HU-Tamas", label: "Hungarian (Hungary) - Tamas" },
  { value: "id-ID-Ardi", label: "Indonesian (Indonesia) - Ardi" },
  { value: "id-ID-Gadis", label: "Indonesian (Indonesia) - Gadis" },
  { value: "is-IS-Gudrun", label: "Icelandic (Iceland) - Gudrun" },
  { value: "is-IS-Gunnar", label: "Icelandic (Iceland) - Gunnar" },
  { value: "it-IT-Diego", label: "Italian (Italy) - Diego" },
  { value: "it-IT-Elsa", label: "Italian (Italy) - Elsa" },
  { value: "it-IT-Giuseppe", label: "Italian (Italy) - Giuseppe" },
  { value: "it-IT-Isabella", label: "Italian (Italy) - Isabella" },
  { value: "ja-JP-Keita", label: "Japanese (Japan) - Keita" },
  { value: "ja-JP-Nanami", label: "Japanese (Japan) - Nanami" },
  { value: "jv-ID-Dimas", label: "Javanese (Indonesia) - Dimas" },
  { value: "jv-ID-Siti", label: "Javanese (Indonesia) - Siti" },
  { value: "ka-GE-Eka", label: "Georgian (Georgia) - Eka" },
  { value: "ka-GE-Giorgi", label: "Georgian (Georgia) - Giorgi" },
  { value: "kk-KZ-Aigul", label: "Kazakh (Kazakhstan) - Aigul" },
  { value: "kk-KZ-Daulet", label: "Kazakh (Kazakhstan) - Daulet" },
  { value: "km-KH-Piseth", label: "Khmer (Cambodia) - Piseth" },
  { value: "km-KH-Sreymom", label: "Khmer (Cambodia) - Sreymom" },
  { value: "kn-IN-Gagan", label: "Kannada (India) - Gagan" },
  { value: "kn-IN-Sapna", label: "Kannada (India) - Sapna" },
  { value: "ko-KR-Hyunsu", label: "Korean (Korea) - Hyunsu" },
  { value: "ko-KR-InJoon", label: "Korean (Korea) - InJoon" },
  { value: "ko-KR-SunHi", label: "Korean (Korea) - SunHi" },
  { value: "lo-LA-Chanthavong", label: "Lao (Laos) - Chanthavong" },
  { value: "lo-LA-Keomany", label: "Lao (Laos) - Keomany" },
  { value: "lt-LT-Leonas", label: "Lithuanian (Lithuania) - Leonas" },
  { value: "lt-LT-Ona", label: "Lithuanian (Lithuania) - Ona" },
  { value: "lv-LV-Everita", label: "Latvian (Latvia) - Everita" },
  { value: "lv-LV-Nils", label: "Latvian (Latvia) - Nils" },
  { value: "mk-MK-Aleksandar", label: "Macedonian (North Macedonia) - Aleksandar" },
  { value: "mk-MK-Marija", label: "Macedonian (North Macedonia) - Marija" },
  { value: "ml-IN-Midhun", label: "Malayalam (India) - Midhun" },
  { value: "ml-IN-Sobhana", label: "Malayalam (India) - Sobhana" },
  { value: "mn-MN-Bataa", label: "Mongolian (Mongolia) - Bataa" },
  { value: "mn-MN-Yesui", label: "Mongolian (Mongolia) - Yesui" },
  { value: "mr-IN-Aarohi", label: "Marathi (India) - Aarohi" },
  { value: "mr-IN-Manohar", label: "Marathi (India) - Manohar" },
  { value: "ms-MY-Osman", label: "Malay (Malaysia) - Osman" },
  { value: "ms-MY-Yasmin", label: "Malay (Malaysia) - Yasmin" },
  { value: "mt-MT-Grace", label: "Maltese (Malta) - Grace" },
  { value: "mt-MT-Joseph", label: "Maltese (Malta) - Joseph" },
  { value: "my-MM-Nilar", label: "Burmese (Myanmar) - Nilar" },
  { value: "my-MM-Thiha", label: "Burmese (Myanmar) - Thiha" },
  { value: "nb-NO-Finn", label: "Norwegian Bokmål (Norway) - Finn" },
  { value: "nb-NO-Pernille", label: "Norwegian Bokmål (Norway) - Pernille" },
  { value: "ne-NP-Hemkala", label: "Nepali (Nepal) - Hemkala" },
  { value: "ne-NP-Sagar", label: "Nepali (Nepal) - Sagar" },
  { value: "nl-BE-Arnaud", label: "Dutch (Belgium) - Arnaud" },
  { value: "nl-BE-Dena", label: "Dutch (Belgium) - Dena" },
  { value: "nl-NL-Colette", label: "Dutch (Netherlands) - Colette" },
  { value: "nl-NL-Fenna", label: "Dutch (Netherlands) - Fenna" },
  { value: "nl-NL-Maarten", label: "Dutch (Netherlands) - Maarten" },
  { value: "pl-PL-Marek", label: "Polish (Poland) - Marek" },
  { value: "pl-PL-Zofia", label: "Polish (Poland) - Zofia" },
  { value: "ps-AF-GulNawaz", label: "Pashto (Afghanistan) - GulNawaz" },
  { value: "ps-AF-Latifa", label: "Pashto (Afghanistan) - Latifa" },
  { value: "pt-BR-Antonio", label: "Portuguese (Brazil) - Antonio" },
  { value: "pt-BR-Francisca", label: "Portuguese (Brazil) - Francisca" },
  { value: "pt-BR-Thalita", label: "Portuguese (Brazil) - Thalita" },
  { value: "pt-PT-Duarte", label: "Portuguese (Portugal) - Duarte" },
  { value: "pt-PT-Raquel", label: "Portuguese (Portugal) - Raquel" },
  { value: "ro-RO-Alina", label: "Romanian (Romania) - Alina" },
  { value: "ro-RO-Emil", label: "Romanian (Romania) - Emil" },
  { value: "ru-RU-Dmitry", label: "Russian (Russia) - Dmitry" },
  { value: "ru-RU-Svetlana", label: "Russian (Russia) - Svetlana" },
  { value: "si-LK-Sameera", label: "Sinhala (Sri Lanka) - Sameera" },
  { value: "si-LK-Thilini", label: "Sinhala (Sri Lanka) - Thilini" },
  { value: "sk-SK-Lukas", label: "Slovak (Slovakia) - Lukas" },
  { value: "sk-SK-Viktoria", label: "Slovak (Slovakia) - Viktoria" },
  { value: "sl-SI-Petra", label: "Slovenian (Slovenia) - Petra" },
  { value: "sl-SI-Rok", label: "Slovenian (Slovenia) - Rok" },
  { value: "so-SO-Muuse", label: "Somali (Somalia) - Muuse" },
  { value: "so-SO-Ubax", label: "Somali (Somalia) - Ubax" },
  { value: "sq-AL-Anila", label: "Albanian (Albania) - Anila" },
  { value: "sq-AL-Ilir", label: "Albanian (Albania) - Ilir" },
  { value: "sr-RS-Nicholas", label: "Serbian (Serbia) - Nicholas" },
  { value: "sr-RS-Sophie", label: "Serbian (Serbia) - Sophie" },
  { value: "su-ID-Jajang", label: "Sundanese (Indonesia) - Jajang" },
  { value: "su-ID-Tuti", label: "Sundanese (Indonesia) - Tuti" },
  { value: "sv-SE-Mattias", label: "Swedish (Sweden) - Mattias" },
  { value: "sv-SE-Sofie", label: "Swedish (Sweden) - Sofie" },
  { value: "sw-KE-Rafiki", label: "Swahili (Kenya) - Rafiki" },
  { value: "sw-KE-Zuri", label: "Swahili (Kenya) - Zuri" },
  { value: "sw-TZ-Daudi", label: "Swahili (Tanzania) - Daudi" },
  { value: "sw-TZ-Rehema", label: "Swahili (Tanzania) - Rehema" },
  { value: "ta-IN-Pallavi", label: "Tamil (India) - Pallavi" },
  { value: "ta-IN-Valluvar", label: "Tamil (India) - Valluvar" },
  { value: "ta-LK-Kumar", label: "Tamil (Sri Lanka) - Kumar" },
  { value: "ta-LK-Saranya", label: "Tamil (Sri Lanka) - Saranya" },
  { value: "ta-MY-Kani", label: "Tamil (Malaysia) - Kani" },
  { value: "ta-MY-Surya", label: "Tamil (Malaysia) - Surya" },
  { value: "ta-SG-Anbu", label: "Tamil (Singapore) - Anbu" },
  { value: "ta-SG-Venba", label: "Tamil (Singapore) - Venba" },
  { value: "te-IN-Mohan", label: "Telugu (India) - Mohan" },
  { value: "te-IN-Shruti", label: "Telugu (India) - Shruti" },
  { value: "th-TH-Niwat", label: "Thai (Thailand) - Niwat" },
  { value: "th-TH-Premwadee", label: "Thai (Thailand) - Premwadee" },
  { value: "tr-TR-Ahmet", label: "Turkish (Turkey) - Ahmet" },
  { value: "tr-TR-Emel", label: "Turkish (Turkey) - Emel" },
  { value: "uk-UA-Ostap", label: "Ukrainian (Ukraine) - Ostap" },
  { value: "uk-UA-Polina", label: "Ukrainian (Ukraine) - Polina" },
  { value: "ur-IN-Gul", label: "Urdu (India) - Gul" },
  { value: "ur-IN-Salman", label: "Urdu (India) - Salman" },
  { value: "ur-PK-Asad", label: "Urdu (Pakistan) - Asad" },
  { value: "ur-PK-Uzma", label: "Urdu (Pakistan) - Uzma" },
  { value: "uz-UZ-Madina", label: "Uzbek (Uzbekistan) - Madina" },
  { value: "uz-UZ-Sardor", label: "Uzbek (Uzbekistan) - Sardor" },
  { value: "vi-VN-HoaiMy", label: "Vietnamese (Vietnam) - HoaiMy" },
  { value: "vi-VN-NamMinh", label: "Vietnamese (Vietnam) - NamMinh" },
  { value: "zh-CN-Xiaoxiao", label: "Chinese (Mandarin, Simplified) - Xiaoxiao" },
  { value: "zh-CN-Xiaoyi", label: "Chinese (Mandarin, Simplified) - Xiaoyi" },
  { value: "zh-CN-Yunjian", label: "Chinese (Mandarin, Simplified) - Yunjian" },
  { value: "zh-CN-Yunxi", label: "Chinese (Mandarin, Simplified) - Yunxi" },
  { value: "zh-CN-Yunxia", label: "Chinese (Mandarin, Simplified) - Yunxia" },
  { value: "zh-CN-Yunyang", label: "Chinese (Mandarin, Simplified) - Yunyang" },
  { value: "zh-CN-liaoning-Xiaobei", label: "Chinese (Mandarin, Simplified) - liaoning-Xiaobei" },
  { value: "zh-CN-shaanxi-Xiaoni", label: "Chinese (Mandarin, Simplified) - shaanxi-Xiaoni" },
  { value: "zh-HK-HiuGaai", label: "Chinese (Cantonese, Traditional) - HiuGaai" },
  { value: "zh-HK-HiuMaan", label: "Chinese (Cantonese, Traditional) - HiuMaan" },
  { value: "zh-HK-WanLung", label: "Chinese (Cantonese, Traditional) - WanLung" },
  { value: "zh-TW-HsiaoChen", label: "Chinese (Taiwanese Mandarin) - HsiaoChen" },
  { value: "zh-TW-HsiaoYu", label: "Chinese (Taiwanese Mandarin) - HsiaoYu" },
  { value: "zh-TW-YunJhe", label: "Chinese (Taiwanese Mandarin) - YunJhe" },
  { value: "zu-ZA-Thando", label: "Zulu (South Africa) - Thando" },
  { value: "zu-ZA-Themba", label: "Zulu (South Africa) - Themba" },
];
